# Generated by Django 5.1.3 on 2024-12-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='images/book_covers/default.jpg', upload_to='book_covers/'),
        ),
    ]
