# Generated by Django 5.1.3 on 2024-12-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='images/book_covers/default.jpg', null=True, upload_to='book_covers/'),
        ),
    ]
