# Generated by Django 5.1.3 on 2025-01-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, default='book_covers/default_cover.jpg', null=True, upload_to='book_covers/'),
        ),
    ]
